### ISSUE TITLE
Add repo to LEDE 17.01.0

### ISSUE THREAD

**Issue by MurkBRA** [stangri/openwrt-repo#1]
I'm trying but no success.
This repository is working?
I tried this code
```
echo -e -n 'untrusted comment: public key 7ffc7517c4cc0c56\nRWR//HUXxMwMVnx7fESOKO7x8XoW4/dRidJPjt91hAAU2L59mYvHy0Fa\n' > /tmp/stangri-repo.pub && opkg-key add /tmp/stangri-repo.pub
! grep -q 'stangri_repo' /etc/opkg/customfeeds.conf && echo 'src/gz stangri_repo https://raw.githubusercontent.com/stangri/openwrt-repo/master' >> /etc/opkg/customfeeds.conf
opkg update
```
I tried add from luci web ui custom source but fails when I try update the packages list from `https://raw.githubusercontent.com/stangri/openwrt-repo/master`

**Comment by stangri** [comment]
Post the output when you run quoted commands.

**Comment by MurkBRA** [comment]
Downloading https://raw.githubusercontent.com/stangri/openwrt-repo/master/Packages.gz
wget: SSL support not available, please install one of the libustream-ssl-* libraries as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://raw.githubusercontent.com/stangri/openwrt-repo/master/Packages.gz

**Comment by MurkBRA** [comment]
Hey, I got here. This msg don't show at the first time.
Thank you. Fast replay.

**Comment by stangri** [comment]
Thank you for your report, I've appended install instructions with information on libustream install.

**Comment by MurkBRA** [comment]
I'm new on all of this custom firmware world (3 days now) but I read somewhere about the command line with putty/kitty, would be nice if you introduce by the beginning like "use this program to do this command" and so on. Your adblock is much better that the one on repo of LEDE, intuitive and fully customizable. And if you what bring translate to this adblock I can help with portuguese of Brazil (pt-br).
And finally, you know this project [here](https://github.com/StevenBlack/hosts).
Project introduction:
> This repository consolidates several reputable hosts files, and merges them into a unified hosts file with duplicates removed. This repo provides several hosts files tailored to you need to block.

**Comment by stangri** [comment]
I don't run Windows so I can't recommend/endorse any specific programs nor provide instructions on how to use SSH in Windows. On Mac/Linux the terminal app is built in and familiar to users with the skill level required to flash custom firmware.

As far as simple-adblock is concerned...

I would be grateful for the translation to Portuguese, the template file can be downloaded [here](https://github.com/stangri/openwrt-luci/tree/luci-app-simple-adblock/applications/luci-app-simple-adblock/po/templates). I haven't done any translations myself, so you would have to google the tools/format if you want to help.

Finally, I am aware of Steven Black's lists, one of his lists can replace at least two (mvps and yoyo) of the default lists in the simple-adblock config, however before I modify the default config I'll need to do a bit more testing. Also, both mvps and yoyo adblock lists are way more popular than Steven Black's list, so if I were to remove them, I'm afraid I'd be getting requests to include them.

With the Web UI you can totally remove/add any lists you want tho.

**Comment by MurkBRA** [comment]
[translate to pt-br](https://drive.google.com/file/d/0B2W9FVeB3EKDdjVuQmJqOUNmLTg/view?usp=drivesdk)

**Comment by stangri** [comment]
Thanks, I got the translation, I'll reach out when I get into the luci app.

**Comment by stangri** [comment]
Thank you! Figured out how it works, please run:
```sh
opkg update; opkg install opkg install luci-i18n-simple-adblock-pt
```

Let me know how it works.

**Comment by MurkBRA** [comment]
`Collected errors:
opkg_install_cmd: Cannot install package install.
`
He don't work but show up on installed programs.
About the opkg name put pt-br like this example here:
![transtale base pack names](http://i.imgur.com/3RSA1zE.png)

**Comment by stangri** [comment]
You must have used the command from the e-mail, please use the command quoted above.

**Comment by MurkBRA** [comment]
Yes, it's installed but no apply any translation.

**Comment by stangri** [comment]
Please try ```opkg update; opkg install luci-i18n-simple-adblock-pt-br```

**Comment by MurkBRA** [comment]
Nice, now it worked very well.

**Comment by stangri** [comment]
Fantastic, thank you for the translation, the testing and your patience! The whole OpenWrt/LEDE localization is pretty new to me, I assumed pt would cover both pt-pt and pt-br. It is surprising that pt is actually pt-pt given the drastic population difference between Portugal and Brazil. ;)

**Comment by MurkBRA** [comment]
Thank you too.
