### ISSUE TITLE
vpn-policy-routing package missing in repo

### ISSUE THREAD

**Issue by Lin4fun** [stangri/openwrt-repo#10]
Hi,

for the first, thanks for your brilliant job! I am using this package and other from your repo since you started. it solved a lot of problems I had!

The package vpn-policy-routing is missing in repo. I tried to install it on a fresh flash but could not find the package so I get the error unkown package.

Is there a problem with this package or will you put it online again soon?

THX!

//Thomas

**Comment by stangri** [comment]
Thanks for noticing. Fixed.
