### ISSUE TITLE
Can't add this repo to the feeds list to compile OpenWrt

### ISSUE THREAD

**Issue by iAbadia** [stangri/openwrt-repo#12]
I tried to compile OpenWrt with some of the packages on this repo (vpn-policy-routing and luci-app-vpn-policy-routing) but could't find the way to correctly add it to the feeds.

The instructions on the webpage are for the Image Builder and SDK. I didn't figure out the way to do it by adding the repo to the file `feeds.conf.default`. When later running `make menuconfig`, the packages showed nowhere.

The way I did it was adding the git repo url preceded by the key src-git like:
`src-git stangri_repo https://github.com/stangri/openwrt_packages.git`

I ended up giving up and deciding to install it manually once the binary was flashed but I encountered #11

**Comment by stangri** [comment]
It is not designed to be added to the feeds. Check the README.
