### ISSUE TITLE
Can't install simple-adblock "Signature check failed."

### ISSUE THREAD

**Issue by ramgp** [stangri/openwrt-repo#2]
executing `opkg update` returns the following:

Downloading https://raw.githubusercontent.com/stangri/openwrt-repo/master/Packages.gz
Updated list of available packages in /var/opkg-lists/stangri_repo
Downloading https://raw.githubusercontent.com/stangri/openwrt-repo/master/Packages.sig
Signature check failed.
Remove wrong Signature file.

**Comment by stangri** [comment]
Please post the output of ```cat /etc/banner```.

**Comment by ramgp** [comment]
`cat /etc/banner`
```
     _________
    /        /\      _    ___ ___  ___
   /  LE    /  \    | |  | __|   \| __|
  /    DE  /    \   | |__| _|| |) | _|
 /________/  LE  \  |____|___|___/|___|                      lede-project.org
 \        \   DE /
  \    LE  \    /  -----------------------------------------------------------
   \  DE    \  /    Reboot (17.01.2, r3435-65eec8bd5f)
    \________\/    -----------------------------------------------------------
```

I don't get how this will help

**Comment by stangri** [comment]
To rule out ancient OS.

I cannot reproduce it. I've deleted the key and repo, ran ```opkg update``` and then re-added the key and repo and ran ```opkg update``` again and didn't get any errors.

How did you add the repo to your router? Were there any errors during any of the steps while adding it? Can you re-run the steps and do the ```opkg update``` again?

**Comment by ramgp** [comment]
I follow the instructions in the README. Interesting I removed the repo, deleted the key from both `/tmp` and from `/etc/opkg/keys` and executed the commands again and it looks like it works.

**Comment by ramgp** [comment]
I got an error during installation. I don't know if it's related.

```

**Comment by ramgp** [comment]
nvm I found that I needed to use the Web UI to enable it. Thanks for you help. We are up and running.
