### ISSUE TITLE
Update LuCI Rosy Theme Package

### ISSUE THREAD

**Issue by boktai1000** [stangri/openwrt-repo#3]
Thanks for creating a great repository! It seems the LuCI Rosy Theme has been updated and since been included in mainline builds. I'm continuing to use your repository in the interim, and appreciate the IPK Package inclusions.

I was wondering if there would be a way to get a current / latest build of the LuCI Rosy Theme included?

Please see the following links to view the UI changes as well as forum thread regarding some of the other changes to the theme since then:
* https://forum.openwrt.org/t/luci-theme-rosy-here-we-go-rosy-them-v3-released/23870 
* https://github.com/rosywrt/luci-theme-rosy

Thanks again!

**Comment by stangri** [comment]
Updated to current version. It's a manual process tho, so I'd recommend you grab an IPK from the snapshot branch if my version is behind.

**Comment by boktai1000** [comment]
Hi @stangri -

Thank you for updating this! I do have a question and potentially another request for you though. Do you have a link or more information on how I can grab an IPK of the latest version from the snapshot branch? I couldn't find a link to it. I also do realize that I don't want to be annoying or bugging you any time that the Rosy theme may update and have to open a new request to have you update your package, so maybe understanding how to get a hold of it would definitely help!

That being said, it appears that the Rosy theme has fixed a number of small graphical issues such as issues displaying Memory usage in the web interface, so even though you recently created a new IPK less than a month ago, it would be excellent to get a new one to resolve these issues.

- https://github.com/rosywrt/luci-theme-rosy/issues/22 
- https://github.com/rosywrt/luci-theme-rosy/issues/24 
- https://github.com/rosywrt/luci-theme-rosy/issues/30
- https://github.com/rosywrt/luci-theme-rosy/issues/28 

I've been following the theme for a bit now, and it's actually being included in OpenWrt third party builds by @davidc502 . What makes your IPK enticing to use though, is that for anyone who wants to use the official build for their router does not have this theme installed by default, so rely on having an IPK to pull from to install for ease of use, and your IPK is the "go-to".

Thanks for taking the time to read my comment, for your work and assistance on this. It is greatly appreciated having a modern user interface to work with in a home router, I would say this rivals the looks of Advanced Tomato.

**Comment by boktai1000** [comment]
Thank you so much and appreciate the heads up on the command! Maybe I'm oblivious or missing something though, but I don't see the IPK in your repository. I checked the latest commit, and it seems an update to PACKAGES (etc) related files, but didn't see the install-able binary. My apologies if it's still in process of being uploaded, but also maybe something was overlooked. Anyways thank you again for your work and hopefully my request wasn't too much of an annoyance for you, it's appreciated! 👍

**Comment by stangri** [comment]
Sorry, I built it but forgot to push to repo. ;)
Should be there now.
