### ISSUE TITLE
cant add repo

### ISSUE THREAD

**Issue by kavillock** [stangri/openwrt-repo#5]
i tried add repo on openwrt 18.06, added keys like in readme but get this response when update lists:

 * opkg_download: Failed to download https://raw.githubusercontent.com/stangri/openwrt-repo/master/Packages.gz, wget returned 5.

**Comment by stangri** [comment]
https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
Error 5 is the SSL verification error. Make sure that wget is configured to support https.
