### ISSUE TITLE
Cannot find vpn-policy-routing package during opkg install

### ISSUE THREAD

**Issue by czsmith** [stangri/openwrt-repo#6]
I am trying to install vpn-policy-routing and luci-app-vpn-policy-routing using the instructions I found on GitHub.

I am attempting this on a GL-iNet MT300N router running OpenWRT 18.6.4.

Your repository was successfully added to /etc/opkg/customfeeds.conf:
```
# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
src/gz stangri_repo https://raw.githubusercontent.com/stangri/openwrt-repo/master
```

When I run opkg install vpn-policy-routing I get the following:
```
root@GL-MT300N-V2:~# opkg install vpn-policy-routing -V3 | grep -e "policy"
opkg_prepare_url_for_install: applying abpkg flag to vpn-policy-routing
pkg_hash_load_package_details_helper: found yet incomplete flagged abpkg vpn-policy-routing
pkg_hash_load_package_details_helper: skipping already seen flagged abpkg vpn-policy-routing
Unknown package 'vpn-policy-routing'.
Collected errors:
 * opkg_install_cmd: Cannot install package vpn-policy-routing.
root@GL-MT300N-V2:~# 
```
Looking at the okg source, that "applying abpkg flag" message is associated with flagging the package state as SF_NEED_DETAIL and the presence of that flag indicates an error and the package is not loaded.

I am running version 3b417b9f41b4ceb5912d82f867dd5534e5675b5c (2017-12-07) of opkg.

Is there something wrong with the repository or its packages.gz file?

I've attached a -V4 opkg output to see if this helps.

Thanks...

[opkg install debug.txt](https://github.com/stangri/openwrt-repo/files/3464226/opkg.install.debug.txt)

**Comment by stangri** [comment]
What happens if you just scp packages to the router and install that way?

**Comment by czsmith** [comment]
I'll give that a try once I figure how to do it.  Relatively new at OpenWRT.

I presume I have to build the vpn-policy-routing URL, wget it then run opkg locally, right?

**Comment by stangri** [comment]
Yes, or download to your computer and scp from there.

**Comment by czsmith** [comment]
Traced problem to network problem reaching repository.
