### ISSUE TITLE
error with luci-app-vpn-polic routing

### ISSUE THREAD

**Issue by oaldahir** [stangri/openwrt-repo#9]
Hi,

I'm getting an error when I click "add" in the web interface when trying to add a new policy. 

I get a web page with the following error.

_Failed to execute cbi dispatcher target for entry '/admin/services/vpn-policy-routing'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:165: Datatype error, bad token "'"
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/cbi.lua:165: in function 'compile_datatype'
	/usr/lib/lua/luci/cbi.lua:177: in function 'compile_datatype'
	/usr/lib/lua/luci/cbi.lua:177: in function 'compile_datatype'
	/usr/lib/lua/luci/cbi.lua:177: in function 'compile_datatype'
	/usr/lib/lua/luci/cbi.lua:189: in function 'verify_datatype'
	/usr/lib/lua/luci/cbi.lua:1497: in function 'validate'
	/usr/lib/lua/luci/cbi.lua:1413: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:1549: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:248: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:1184: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:248: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:387: in function 'parse'
	/usr/lib/lua/luci/dispatcher.lua:856: in function </usr/lib/lua/luci/dispatcher.lua:835>_

I'm using **luci-app-vpn-policy-routing_git-19.284.27115-3688774-62_all.ipk**
with **vpn-policy-routing - 0.2.0-1**
and
Firmware Version **OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc)**
Kernel Version **4.14.131**

Any help would be greatly appreciated.

**Comment by stangri** [comment]
Fixed in https://github.com/stangri/openwrt-repo/blob/master/luci-app-vpn-policy-routing_git-19.287.53084-11e4377-63_all.ipk
